services:
  npc:
    image: ghcr.io/djylb/npc:v0.34.7
    restart: always
    network_mode: host
    command: -server=${NPS_SERVER_ADDR} -vkey=${NPS_VKEY}
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
