services:
  fast-note-sync-service:
    image: haierkeys/fast-note-sync-service:3.6.1
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:9000"
    networks:
      - 1panel-network
    volumes:
      - ./data/storage:/fast-note-sync/storage
      - ./data/config:/fast-note-sync/config
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
