services:
  ani-rss:
    image: wushuo894/ani-rss:v3.2.6
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - PORT=7789
      - CONFIG=/config
      - TZ=Asia/Shanghai
    ports:
      - ${PANEL_APP_PORT_HTTP}:7789
    volumes:
      - ./ani-rss-config:/config
      - ./media:/Media
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: ${CONTAINER_NAME}_qbittorrent
    restart: always
    environment:
      - WEBUI_PORT=8080
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
    ports:
      - 8080:8080
    volumes:
      - ./qbittorrent-config:/config
      - ./downloads:/downloads
      - ./media:/Media
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true
