services:
  caddy:
    container_name: ${CONTAINER_NAME}
    restart: always
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-caddy:2.10-alpine
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/caddy/caddy_config:/config
      - ./data/caddy/caddy_data:/data
      - ./data/caddy/run:/var/run/caddy
    environment:
      - CADDY_ADMIN=unix//var/run/caddy/caddy-admin.sock
    network_mode: host
    labels:
      createdBy: "Apps"

  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    depends_on:
      - api
    restart: always
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-nginx:v3.87.0
    ports:
      - "${PANEL_APP_PORT_HTTPS}:8080"
    volumes:
      - ./data/nginx/ssl:/etc/nginx/ssl
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.111"
        aliases:
          - panda-wiki-nginx
    labels:
      createdBy: "Apps"

  app:
    container_name: ${CONTAINER_NAME}-app
    restart: always
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-app:v3.87.0
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.112"
        aliases:
          - panda-wiki-app
    labels:
      createdBy: "Apps"

  api:
    container_name: ${CONTAINER_NAME}-api
    depends_on:
      - postgres
      - nats
      - caddy
      - raglite
    restart: always
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-api:v3.87.0
    volumes:
      - ./data/caddy/run:/app/run
      - ./data/nginx/ssl:/app/etc/nginx/ssl
      - ./data/conf/api:/data
    environment:
      - NATS_PASSWORD=${NATS_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SUBNET_PREFIX=${SUBNET_PREFIX}
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.2"
        aliases:
          - panda-wiki-api
    labels:
      createdBy: "Apps"

  consumer:
    container_name: ${CONTAINER_NAME}-consumer
    depends_on:
      - nats
      - api
      - raglite
    restart: always
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-consumer:v3.87.0
    environment:
      - NATS_PASSWORD=${NATS_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SUBNET_PREFIX=${SUBNET_PREFIX}
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.3"
        aliases:
          - panda-wiki-consumer
    labels:
      createdBy: "Apps"

  postgres:
    container_name: ${CONTAINER_NAME}-postgres
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/postgres-zhparser:17.6-bookworm
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "panda-wiki", "-d", "panda-wiki"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=panda-wiki
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=panda-wiki
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.10"
        aliases:
          - panda-wiki-postgres
    labels:
      createdBy: "Apps"

  redis:
    container_name: ${CONTAINER_NAME}-redis
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-redis:7.4.2-alpine
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--appendfilename", "appendonly.aof", "--save", "900 1", "--save", "300 10", "--save", "60 10000"]
    volumes:
      - ./data/redis:/data
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.11"
        aliases:
          - panda-wiki-redis
    labels:
      createdBy: "Apps"

  minio:
    container_name: ${CONTAINER_NAME}-minio
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    restart: always
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ACCESS_KEY=s3panda-wiki
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.12"
        aliases:
          - panda-wiki-minio
    labels:
      createdBy: "Apps"

  nats:
    container_name: ${CONTAINER_NAME}-nats
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-nats:2.11.3-alpine
    restart: always
    command: ["nats-server", "-c", "/etc/nats/nats.conf", "--user", "panda-wiki", "--pass", "${NATS_PASSWORD}"]
    volumes:
      - ./data/nats:/data
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.13"
        aliases:
          - panda-wiki-nats
    labels:
      createdBy: "Apps"

  qdrant:
    container_name: ${CONTAINER_NAME}-qdrant
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-qdrant:v1.14.1
    restart: always
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.14"
        aliases:
          - panda-wiki-qdrant
    labels:
      createdBy: "Apps"

  crawler:
    container_name: ${CONTAINER_NAME}-crawler
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/anydoc:v0.9.11
    restart: always
    init: true
    environment:
      - GLOG_GLOBAL_LEVEL=info
      - NAMESPACE=anydoc
      - MQ_NATS_URL=nats://panda-wiki-nats:4222
      - MQ_NATS_USER=panda-wiki
      - MQ_NATS_PASSWORD=${NATS_PASSWORD}
      - OSS_MINIO_ACCESS_KEY=s3panda-wiki
      - OSS_MINIO_SECRET_KEY=${S3_SECRET_KEY}
      - OSS_MINIO_ENDPOINT=panda-wiki-minio:9000
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.17"
        aliases:
          - panda-wiki-crawler
    labels:
      createdBy: "Apps"

  raglite:
    container_name: ${CONTAINER_NAME}-raglite
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/raglite:v2.17.0
    restart: always
    depends_on:
      - postgres
      - minio
      - qdrant
    volumes:
      - ./data/raglite:/data
    environment:
      - GIN_MODE=release
      - DATABASE_POSTGRESQL_HOST=panda-wiki-postgres
      - DATABASE_POSTGRESQL_USER=panda-wiki
      - DATABASE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_QDRANT_HOST=panda-wiki-qdrant
      - DATABASE_QDRANT_API_KEY=${QDRANT_API_KEY}
      - STORAGE_MINIO_ENDPOINT=panda-wiki-minio:9000
      - STORAGE_MINIO_ACCESS_KEY_ID=s3panda-wiki
      - STORAGE_MINIO_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - NATS_URL=nats://panda-wiki-nats:4222
      - NATS_USER=panda-wiki
      - NATS_PASSWORD=${NATS_PASSWORD}
      - EMBEDDER_RPM=800
      - LLM_RPM=50
    networks:
      panda-wiki:
        ipv4_address: "${SUBNET_PREFIX:-169.254.15}.18"
        aliases:
          - panda-wiki-raglite
    labels:
      createdBy: "Apps"

networks:
  panda-wiki:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET_PREFIX:-169.254.15}.0/24"
  1panel-network:
    external: true
