services:
  speaches:
    image: ghcr.io/speaches-ai/speaches:0.8.3-cuda
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${HOST_IP}:${PANEL_APP_PORT_HTTP}:8000"
    volumes:
      - ./data/hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
    environment:
      - API_KEY=${SECRET_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
