services:
  rsshub:
    image: diygod/rsshub:chromium-bundled-2026-08-22
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://:${PANEL_REDIS_ROOT_PASSWORD}@redis:6379/"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_NAME}-redis
    restart: always
    command: ["redis-server", "--requirepass", "${PANEL_REDIS_ROOT_PASSWORD}", "--appendonly", "yes"]
    environment:
      REDISCLI_AUTH: "${PANEL_REDIS_ROOT_PASSWORD}"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
