services:
  9router:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:20128"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - DATA_DIR=/app/data
      - PORT=20128
      - HOSTNAME=0.0.0.0
    image: decolua/9router:0.5.59
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
