services:
  git-sync:
    image: ghcr.io/akashrajpurohit/git-sync:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${GITSYNC_CONFIG_PATH}:/git-sync/config.yaml
      - ${GITSYNC_BACKUP_PATH}:/backups
    restart: always
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true
