services:
  omniroute:
    image: diegosouzapw/omniroute:3.8.50
    container_name: ${CONTAINER_NAME}
    restart: always
    stop_grace_period: 40s
    ports:
      - "${PANEL_APP_PORT_HTTP}:20128"
      - "${PANEL_APP_PORT_API}:20129"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=20128
      - DASHBOARD_PORT=20128
      - API_PORT=20129
      - API_HOST=0.0.0.0
      - HOSTNAME=0.0.0.0
      - DATA_DIR=/app/data
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY_SECRET=${API_KEY_SECRET}
      - INITIAL_PASSWORD=${INITIAL_PASSWORD}
      - REQUIRE_API_KEY=${REQUIRE_API_KEY}
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
